server:
  port: 9000

springdoc:
  api-docs:
    path: /api-docs

# http://localhost:9000/swagger-ui.html
  swagger-ui:
    path: /swagger-ui.html

#    클라이언트
url:
  base: http://localhost:8080 

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fitmate?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
#      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
#  quartz:
#    job-store-type: jdbc
#    properties.org.quartz.threadPool.threadCount: 5

#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
logging:
  level:
    org:
      springframework.web.client: DEBUG
      hibernate.SQL: DEBUG
      hibernate.type: trace

jwt:
  header: Authorization
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
  token-validity-in-seconds: 86400          # 1일
  token-refresh-in-seconds: 1000*60*60*24*7 # 1주일

social:
  kakao:
    client-id: 30fb9b59db516bf7c56055b26f8daf47
    redirect: http://localhost:8080
    url:
      login: https://kauth.kakao.com/oauth/authorize
      token: https://kauth.kakao.com/oauth/token
      profile: https://kapi.kakao.com/v2/user/me
      unlink: https://kapi.kakao.com/v1/user/unlink
  password: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
cloud:
  aws:
    credentials:
      accessKey: AKIAWVRECJEE5G74RTEV
      secretKey: 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
    s3:
      bucket: hongjunland
    region:
      static: ap-northeast-2
    stack:
      auto: false

