server:
  port: 9000

springdoc:
  api-docs:
    path: /api-docs

# http://localhost:9000/swagger-ui.html
  swagger-ui:
    path: /swagger-ui.html

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fitmate?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.:
      ddl-auto: create-drop
#      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
logging:
  level:
    org:
      springframework.web.client: DEBUG
      hibernate.SQL: DEBUG
      hibernate.type: trace

jwt:
  header: Authorization
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
  token-validity-in-seconds: 86400          # 1일
  token-refresh-in-seconds: 1000*60*60*24*7 # 1주일

