server:
  port: 9000

springdoc:
  api-docs:
    path: /api-docs

# http://localhost:9000/swagger-ui.html
  swagger-ui:
    path: /swagger-ui.html

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fitmate?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
logging:
  level:
    org.springframework.web.client: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: trace